version: 2.1
executors:
  php72:
    docker:
      - image: circleci/php:7.2
  php73:
    docker:
      - image: circleci/php:7.3
  php74:
    docker:
      - image: circleci/php:7.4
commands:
  deps:
    steps:
      - run:
          name: Install dependencies
          command: composer install
  test:
    steps:
      - run:
          name: Test
          command: vendor/bin/phpunit

jobs:
  php72_build_test:
    executor: php72
    steps:
      - checkout
      - deps
      - test
  php73_build_test:
    executor: php73
    steps:
      - checkout
      - deps
      - test
  php74_build_test:
    executor: php74
    steps:
      - checkout
      - deps
      - test

workflows:
  build_test:
    jobs:
      - php72_build_test
      - php73_build_test
      - php74_build_test
