version: 2.1

jobs:
  php72-build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Test
          command: vendor/bin/phpunit
  php73-build:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Test
          command: vendor/bin/phpunit

workflows:
  build:
    jobs:
      - php72-build
      - php73-build
