version: 2.1
executors:
  php72:
    docker:
      - image: circleci/php:7.2
  php73:
    docker:
      - image: circleci/php:7.3

jobs:
  php72-build:
    executor: php72
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Test
          command: vendor/bin/phpunit
  php73-build:
    executor: php73
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install
      - run:
          name: Test
          command: vendor/bin/phpunit

workflows:
  build:
    jobs:
      - php72-build
      - php73-build
